### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Jugador-Ganador-en-Python#3]
- Se recomienda uso de clases y tratamiento de errores
- Al ejecutar el programa en python, e ingresar el archivo enviar un error no tratado

python exercise.py 
Por favor escriba el nombre del archivo: ../../../../Documents/Tests/casos/P1-CP1-EntradaEjemplo.txt 
Traceback (most recent call last):
  File "exercise.py", line 3, in <module>
    routeFile = input('Por favor escriba el nombre del archivo: ')
  File "<string>", line 1
    ../../../../Documents/Tests/casos/P1-CP1-EntradaEjemplo.txt 
    ^
SyntaxError: invalid syntax

**Comment by Arcont01** [comment]
Ya arregle problemas e implementación de clases
