### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Jugador-Ganador-en-Python#4]
- Se recomienda uso de clases y tratamiento de errores
- Las condiciones del calculo no están correctamente implementadas

**Comment by Arcont01** [comment]
Se estan usando clases y se estan comprobando posibles errores

**Comment by Arcont01** [comment]
Es posible que me des mas detalles de a que te refieres a usar clases ya que se estan implementando

**Comment by nbxandresvejar** [comment]
Es correcto, solo revisa los otros puntos por favor. Saludos

**Comment by Arcont01** [comment]
Se validan que los números unicamente puedan ser números enteros y se hace cambios en el calculo de diferencia de puntos, así como se crea un log de posibles errores o errores inesperados
